# Generated by Django 4.2.1 on 2023-06-02 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('idabsence', models.SmallAutoField(primary_key=True, serialize=False)),
                ('idetudiant', models.SmallIntegerField(blank=True, null=True)),
                ('idcour', models.SmallIntegerField(blank=True, null=True)),
                ('justifier', models.TextField(blank=True, null=True)),
                ('justification', models.CharField(blank=True, max_length=5000, null=True)),
            ],
            options={
                'db_table': 'absence',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('idcours', models.SmallAutoField(primary_key=True, serialize=False)),
                ('titre_cours', models.CharField(blank=True, max_length=40, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('idenseignant', models.SmallIntegerField(blank=True, null=True)),
                ('duree', models.TimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cours',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Enseigant',
            fields=[
                ('idenseignant', models.SmallAutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, max_length=40, null=True)),
                ('prenom', models.CharField(blank=True, max_length=40, null=True)),
                ('email', models.CharField(blank=True, db_collation='utf8mb3_general_ci', max_length=255, null=True)),
            ],
            options={
                'db_table': 'enseigant',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('idetudiant', models.SmallAutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, max_length=40, null=True)),
                ('prenom', models.CharField(blank=True, max_length=40, null=True)),
                ('email', models.CharField(blank=True, db_collation='utf8mb3_general_ci', max_length=255, null=True)),
                ('idgroupe', models.SmallIntegerField(blank=True, null=True)),
                ('photo', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'etudiant',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('idgroupe', models.SmallAutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'groupe',
                'managed': False,
            },
        ),
    ]
