# Generated by Django 4.2.1 on 2023-06-07 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sae23', '0002_alter_absence_justification_alter_etudiant_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='justifier',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
