# Generated by Django 4.2.1 on 2023-06-08 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sae23', '0002_alter_etudiant_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photo/'),
        ),
    ]
